version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    env_file: .env
    restart: unless-stopped

volumes:
  node_modules:
